export const dungeonConfig = {
    width: 16,
    height: 16,
    a: () => [sprite("block"), "wall", area(), solid()],
    b: () => [sprite("bombable-block"), area(), "bombable-block"],
    "}": () => [
        sprite("skeleton"),
        "skeleton",
        "dangerous",
        area(),
        solid(),
        { dir: -1, timer: 0 },
    ],
    x: () => [sprite("bomb"), area(), solid(), "bomb"],
    k: () => [sprite("key"), area(), solid(), "key"],
    è: () => [sprite("slicer"), "slicer", "dangerous", area(), { dir: -1 }],
    $: () => [sprite("snake"), "snake", "dangerous", area(), { dir: -1 }],
    "|": () => [sprite("locked-door1"), "locked-door1", area()],
    ")": () => [sprite("locked-door2")],
    "&": () => [sprite("left-statue"), area(), solid()],
    "@": () => [sprite("right-statue"), area(), solid()],
    "<": () => [sprite("upstairs"), area(), "previous-level"],
    ">": () => [sprite("downstairs"), area(), "next-level"],
    o: () => [sprite("oldman"), area(), "oldman"],
    "#": () => [sprite("door-open"), area(), "go-locked-room"],
    e: () => [sprite("exit"), area(), "back-main-level"],
    "*": () => [sprite("hole"), area(), "room4"],
};

export const dungeonMaps = [
    [
        "aaaaaaaaaaaaaaaa",
        "a  &        @  a",
        "a    x         a",
        "a              a",
        "a  a     >  a  a",
        "a  a    }   a  a",
        "b  a        a  |",
        "b  a        a  )",
        "a  a        a  a",
        "a  a        a  a",
        "a  a}       a  a",
        "a              a",
        "a          è   a",
        "a  &       @   a",
        "aaaaaaaaaaaaaaaa",
    ],
    [
        "aaaaaaaaaaaaaaaa",
        "a&            @a",
        "a <            a",
        "a              a",
        "a  aaaaaaaaaa  a",
        "a  a$       a  a",
        "a  a        a  a",
        "a  a   k    a  a",
        "a  a        a  a",
        "a  a       $a  a",
        "a  aa      aa  a",
        "a    x         a",
        "a          è   a",
        "a&            @a",
        "aaaaaaaaaaaaaaaa",
    ],
    [
        "aaaaaaaaaaaaaaaa",
        "a&            @a",
        "a              a",
        "a              a",
        "a  aaaaaaaaaa  a",
        "a  a        a  a",
        "a  a    o   a  a",
        "e  aa      aa  a",
        "e              a",
        "a              a",
        "a              a",
        "a              a",
        "a              a",
        "a&            @a",
        "aaaaaaaaaaaaaaaa",
    ],
    [
        "aaaaaaaaaaaaaaaa",
        "a&            @a",
        "a              a",
        "a              a",
        "a  aaaaaaaaaa  a",
        "a  a        a  a",
        "a  a $      a  e",
        "a  a        a  e",
        "a  a     }  a  a",
        "a  a        a  a",
        "a  aa      aa  a",
        "a              a",
        "a              a",
        "a&      è     @a",
        "aaaaaaaaaaaaaaaa",
    ],
];
